backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "wanders"
    label: "JB Wanders"
    folder: "content/wanders"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Location", name: "location", widget: "string", required: false }
      - { label: "Summary", name: "summary", widget: "text", required: false }
      - { label: "Featured Image", name: "featured_image", widget: "image", required: false }
      - { label: "Featured Image Caption", name: "featured_image_caption", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "wonders"
    label: "JB Wonders"
    folder: "content/wonders"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "summary", widget: "text", required: false }
      - { label: "Featured Image", name: "featured_image", widget: "image", required: false }
      - { label: "Featured Image Caption", name: "featured_image_caption", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
